POST http://dev.notifer.org/api/v1/device HTTP/1.1
content-type: application/json

{
    "uuid":"cd21048d-1de8-4a9f-9ad9-8e09f12e1d94",
    "name":"Chathura Wijesinghe"
}


GET http://dev.notifer.org/api/v1/device/ HTTP/1.1


PUT  http://dev.notifer.org/api/v1/device/ HTTP/1.1
content-type: application/json

{
    "uuid":"cd21048d-1de8-4a9f-9ad9-8e09f12e1d94",
    "name":"Wijesinghe S H C D"
}



DELETE  http://dev.notifer.org/api/v1/device/cd21048d-1de8-4a9f-9ad9-8e09f12e1d94 HTTP/1.1
content-type: application/json


## Merchant 

### Create Merchant 

POST http://dev.notifer.org/api/v1/merchant HTTP/1.1
content-type: application/json

{
    "uuid":"cd21048d-1de8-4a9f-9ad9-8e09f12e1d94",
    "name":"Chathura Wijesinghe",
    "url":"http://abc.com",
    "email":"info@persystance.com",
    "address":"Nugegoda"
}

### Update Merchant 

PUT http://dev.notifer.org/api/v1/merchant HTTP/1.1
content-type: application/json

{
    "uuid":"cd21048d-1de8-4a9f-9ad9-8e09f12e1d94",
    "name":"Chathura Wijesinghe",
    "url":"http://trackme.lk",
    "email":"hello@trackme.lk",
    "address":"447/10",
    "postalcode":"10150",
    "country":"Sri Lanka",
    "city":"Athurugiriya",
    "street":"Kottawa Rd",
    "isVerified":true
}

### Retreive Merchant bu ID 

GET  http://dev.notifer.org/api/v1/merchant/cd21048d-1de8-4a9f-9ad9-8e09f12e1d94 HTTP/1.1